# Generated by Django 5.2.17 on 2026-10-05 14:20

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_membership_is_starred_membership_last_viewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover',
            field=models.ImageField(blank=True, help_text='JPG, PNG, WebP or GIF, up to 5 MB.', upload_to=projects.models.cover_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), projects.models.validate_cover_size]),
        ),
    ]
